// Builds the game from src/.
//   node tools/build.js            -> dist/index.html   (standalone, open directly in a browser)
//   node tools/build.js --artifact -> dist/artifact.html (no <html>/<head>/<body>, for Claude artifact publishing)
//   node tools/build.js --web      -> www/               (PWA: index.html + manifest + service worker + icons; also the Capacitor webDir)
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const root = path.join(__dirname, '..');
const read = f => fs.readFileSync(path.join(root, 'src', f), 'utf8');

const body = [
  read('shell.html'),
  '<script>',
  read('engine.js'),
  read('levels.js'),
  read('game.js'),
  '</script>',
].join('\n');

const APP = { name: '부캉이 바다로', short: '부캉이', color: '#0c3340', description: '부산 북항 수로에 들어온 상어 부캉이를 바다로 돌려보내는 슬라이드 퍼즐' };

const page = (head, extra = '') => `<!doctype html>
<html lang="ko">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
${head}</head>
<body style="margin:0">
${body}
${extra}</body>
</html>
`;

function write(rel, content) {
  const file = path.join(root, rel);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
  console.log(`built ${rel} (${(Buffer.byteLength(content) / 1024).toFixed(1)} KB)`);
}

if (process.argv.includes('--artifact')) {
  write('dist/artifact.html', body);
} else if (process.argv.includes('--web')) {
  const head = `<meta name="description" content="${APP.description}">
<meta name="theme-color" content="${APP.color}">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="apple-mobile-web-app-title" content="${APP.short}">
<link rel="manifest" href="manifest.webmanifest">
<link rel="icon" href="icons/icon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="icons/apple-touch-icon.png">
`;
  // Offline support for browsers only; inside the Capacitor app the files are already local.
  const register = `<script>
if ('serviceWorker' in navigator && (location.protocol === 'https:' || location.hostname === 'localhost') && !window.Capacitor) navigator.serviceWorker.register('sw.js').catch(() => {});
</script>
`;
  const html = page(head, register);
  const icons = ['icon-192.png', 'icon-512.png', 'apple-touch-icon.png'];
  const version = crypto.createHash('sha1').update(html).update(icons.map(f => fs.readFileSync(path.join(root, 'assets', 'icons', f))).join('')).digest('hex').slice(0, 10);
  const manifest = {
    name: APP.name, short_name: APP.short, description: APP.description, lang: 'ko',
    start_url: './', scope: './', display: 'standalone', orientation: 'portrait',
    background_color: APP.color, theme_color: APP.color,
    icons: [
      { src: 'icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png' },
      { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  };
  const sw = `// Generated by tools/build.js --web. Bump happens automatically when any cached file changes.
const CACHE = 'bukang-sea-${version}';
const SHELL = ['./', 'index.html', 'manifest.webmanifest', 'icons/icon.svg', ${icons.map(f => `'icons/${f}'`).join(', ')}];
const FONT_HOSTS = ['fonts.googleapis.com', 'fonts.gstatic.com'];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k.startsWith('bukang-sea-') && k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (FONT_HOSTS.includes(url.hostname)) {
    // fonts: serve cached copy, refresh in the background
    e.respondWith(caches.open(CACHE).then(c => c.match(req).then(hit => {
      const net = fetch(req).then(res => { if (res.ok || res.type === 'opaque') c.put(req, res.clone()); return res; }).catch(() => hit);
      return hit || net;
    })));
    return;
  }
  if (url.origin !== location.origin) return;
  if (req.mode === 'navigate') {
    // page: network first so a new build shows up right away, cache when offline
    e.respondWith(fetch(req).then(res => { const copy = res.clone(); caches.open(CACHE).then(c => c.put('index.html', copy)); return res; })
      .catch(() => caches.match('index.html')));
    return;
  }
  e.respondWith(caches.match(req).then(hit => hit || fetch(req)));
});
`;
  write('www/index.html', html);
  write('www/manifest.webmanifest', JSON.stringify(manifest, null, 2) + '\n');
  write('www/sw.js', sw);
  fs.mkdirSync(path.join(root, 'www', 'icons'), { recursive: true });
  fs.copyFileSync(path.join(root, 'assets', 'icon.svg'), path.join(root, 'www', 'icons', 'icon.svg'));
  icons.forEach(f => fs.copyFileSync(path.join(root, 'assets', 'icons', f), path.join(root, 'www', 'icons', f)));
  console.log(`copied icons, cache version ${version}`);
} else {
  write('dist/index.html', page(''));
}
