/* ---------- Pilot course: North Harbor → Sluice Works (12 canals, separate records) ---------- */
// Stable ids p01–p12 key the saved stars, sessions and hint allowance; never renumber or reuse them.
// p = switch, G = gate closed at the start, g = gate open at the start (see engine.js). One link group per canal.
// Each canal records its region, learning intent, role, verified minimum route and star target.
// route: the verified minimum swipes; [x,y] = net placement before that swipe. npm run verify replays it.
const PILOT_VERSION = 1;
const PILOT_REGIONS = [
  { id: 'north-harbor', name: '북항 수로', short: '북항', goal: '굽은 물길을 지나 수문 시설 입구까지 가요.',
    // Board surfaces only; exits, jets, nets, fish and devices keep their shared colors in every region.
    palette: null },
  { id: 'sluice-works', name: '수문 시설', short: '수문', goal: '스위치로 수문을 열고 닫으며 바깥 바다로 나가요.',
    palette: { water: '#287b9e', sea: '#17577b', land: ['#f4f8fa', '#dbe7eb'], seam: '#accbd5', rail: '#f8ffff', park: '#82b7ac', frame: '#93c7d7' } },
];
const PILOT_LEVELS = [
  { id: 'p01', region: 'north-harbor', role: 'learn', name: '부두 모퉁이', par: 7, nets: 0, route: 'U R U L R',
    intent: '부표 앞에서 멈춰 옆 줄로 옮겨 타야 위쪽 물길로 꺾을 수 있다.',
    tip: '부표 앞에서 멈춘 뒤 옆 줄로 옮겨 타 보세요.', map: [
      '########',
      '#f.....E',
      '#......#',
      '#..#####',
      '#o.#####',
      '#..#####',
      '#..#####',
      '#S######',
    ] },
  { id: 'p02', region: 'north-harbor', role: 'learn', name: '위아래 두 방', par: 8, nets: 0, route: 'U R U L R U',
    intent: '아래 방에서 가운데 틈 바로 아래에 멈춰야 위 방으로 건너갈 수 있다.',
    tip: '가운데 틈 아래에서 멈춰야 위 방으로 건너가요.', map: [
      '#####E###',
      '#.f..fo.#',
      '#....o..#',
      '#.......#',
      '###.#####',
      '#...o...#',
      '#.......#',
      '#S#######',
    ] },
  { id: 'p03', region: 'north-harbor', role: 'regular', name: '두 갈래 물길', par: 8, nets: 0, route: 'U R L U R D U',
    intent: '출구로 이어지지 않는 오른쪽 가지의 숭어를 먼저 챙기고 왼쪽 갈래로 돌아 나간다.',
    tip: '두 갈래 중 어느 쪽이 출구로 이어질까요? 숭어도 살펴보세요.', map: [
      '####E####',
      '#....o..#',
      '#.##f##.#',
      '#.##o##.#',
      '#.....f.#',
      '####S####',
    ] },
  { id: 'p04', region: 'north-harbor', role: 'learn', name: '북항 끝 부두', par: 8, nets: 0, route: 'U R D L D U', boundary: true,
    intent: '출구 바로 아래의 숭어를 먹고 같은 줄로 곧장 올라가 북항을 마무리한다.',
    tip: '저 너머가 수문 시설이에요. 출구 아래 숭어도 잊지 마세요.', map: [
      '#####E###',
      '#.......#',
      '#.......#',
      '#.###...#',
      '#.o..f.o#',
      '#...###.#',
      '#.......#',
      '#S#######',
    ] },
  { id: 'p05', region: 'sluice-works', role: 'learn', name: '첫 수문', par: 7, nets: 0, route: 'U L D R U', needsGate: true,
    intent: '닫힌 수문 바로 앞의 스위치에서 멈추면 수문이 열린다.',
    tip: '닫힌 수문 앞 스위치에서 멈추면 수문이 열려요.', map: [
      '####E##',
      '####G##',
      '#f..p.#',
      '#.....#',
      '#.....#',
      '#....##',
      '####S##',
    ] },
  { id: 'p06', region: 'sluice-works', role: 'learn', name: '멈춰야 눌려요', par: 9, nets: 0, route: 'U R D L U R U', needsGate: true,
    intent: '지나가면 눌리지 않으므로, 벽이 위에 있는 방향(아래쪽)에서 올라와 스위치에 멈춘다.',
    tip: '스위치는 지나가기만 하면 눌리지 않아요. 멈출 방법을 찾아보세요.', map: [
      '######E#',
      '######G#',
      '#..p...#',
      '#f#.##.#',
      '#.#..f.#',
      '#S######',
    ] },
  { id: 'p07', region: 'sluice-works', role: 'regular', name: '반대편 스위치', par: 7, nets: 0, route: 'U L U D R U', needsGate: true,
    intent: '보이는 수문 쪽 갈래가 아니라 반대 갈래의 스위치를 먼저 누르고 돌아온다.',
    tip: '수문이 보여도 스위치가 먼저예요. 어느 갈래로 갈까요?', map: [
      '#######E#',
      '#######G#',
      '#.......#',
      '#o#####f#',
      '#p#####.#',
      '#..f....#',
      '####S####',
    ] },
  { id: 'p08', region: 'sluice-works', role: 'regular', name: '닫히는 옆방', par: 9, nets: 0, route: 'R D L R U L R U', needsGate: true,
    intent: '스위치를 누르면 열린 아래 수문이 닫히므로 아래 방의 숭어를 먼저 챙긴다.',
    tip: '스위치를 누르면 열려 있던 아래 수문이 닫혀요. 무엇부터 할까요?', map: [
      '#######E#',
      '#######G#',
      '#p......#',
      '#.......#',
      'S....o..#',
      '####g####',
      '#.......#',
      '#..f.o..#',
      '#########',
    ] },
  { id: 'p09', region: 'sluice-works', role: 'learn', name: '모퉁이 스위치', par: 6, nets: 0, route: 'U R D U', needsGate: true,
    intent: '모퉁이에서 바로 눌리는 스위치로 배운 조작을 빠르게 확인하는 쉬어 가는 판.',
    tip: '잠깐 쉬어 가는 수로예요. 모퉁이 스위치부터 눌러 보세요.', map: [
      '####E##',
      '####G##',
      '#p...o#',
      '#.##..#',
      '#.##..#',
      '#...f.#',
      '#S#####',
    ] },
  { id: 'p10', region: 'sluice-works', role: 'regular', name: '물줄기 수문', par: 7, nets: 0, route: 'U R U D D U', needsGate: true,
    intent: '물줄기가 꺾어 보내는 수문이 닫혀 있으면 그 앞에서 멈추므로, 스위치를 누른 뒤 같은 물줄기를 다시 탄다.',
    tip: '물줄기가 수문 쪽으로 꺾어 줘요. 닫혀 있으면 그 앞에서 멈춰요.', map: [
      '#########',
      '#.....f.#',
      '#oo....##',
      '#.f...>GE',
      '#......##',
      '#.......#',
      '#.....p.#',
      '#S#######',
    ] },
  { id: 'p11', region: 'sluice-works', role: 'regular', name: '그물로 누르기', par: 6, nets: 1, route: 'U R [7,5]D [3,4]L [3,4]U', needsGate: true,
    intent: '넓은 물 한가운데의 스위치는 그물을 너머에 쳐야 그 위에 멈춘다. 숭어를 지나오도록 그물을 옮긴다.',
    tip: '스위치 너머에 그물을 치면 그 위에 멈출 수 있어요.', map: [
      '####E####',
      '####G####',
      '#..o....#',
      '#.......#',
      '#...pff.#',
      '#....o..#',
      '#.......#',
      '####S####',
    ] },
  { id: 'p12', region: 'sluice-works', role: 'challenge', name: '갑문 통과', par: 11, nets: 0, route: 'U R D R L U U L D U R', needsGate: true, finale: true,
    intent: '갑문 안 스위치를 누르면 위 문이 열리고 아래 문이 닫히므로, 아래 물길의 숭어를 먼저 먹고 들어간다.',
    tip: '갑문 안 스위치를 누르면 위 문이 열리고 아래 문은 닫혀요. 마지막 구출!', map: [
      '######E##',
      '#o....^.#',
      '#.......#',
      '#.f.....#',
      '####G####',
      '####p####',
      '####g####',
      '#....o..#',
      '#.......#',
      '#..o..f.#',
      '#S#######',
    ] },
];
if (typeof module !== 'undefined') module.exports = { PILOT_VERSION, PILOT_REGIONS, PILOT_LEVELS };
